name: Update Codewars Stats
on:
  schedule:
    - cron: '0 0 * * *' # Daily update
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Stats updated on $(date)" >> README.md
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Update Codewars stats"
          git push
